### ISSUE TITLE
Read filters don't work with the * operator

### ISSUE THREAD

**Issue by davidvgalbraith** [juttle/juttle#483] opened 2016-02-29 23:45 UTC
If you do `read stochastic -source "cdn" -nhosts 3 -from Date.new(0) -to Date.new(60) *"host"="sea.0"` you get 
```
CompileError: Invalid filter term. Valid forms are: "field == value", "value == field".
      at Object.compileError (lib/errors.js:76:12)
      at StaticFilterChecker.visitExpressionFilterTerm (lib/compiler/filters/static-filter-checker.js:137:26)
      at StaticFilterChecker.visit (lib/compiler/ast-visitor.js:111:42)
      at lib/compiler/ast-visitor.js:206:28
      at Array.forEach (native)
      at StaticFilterChecker.ASTVisitor.(anonymous function) [as visitBinaryExpression] (lib/compiler/ast-visitor.js:196:29)
      at StaticFilterChecker.visit (lib/compiler/ast-visitor.js:111:42)
      at StaticFilterChecker.check (lib/compiler/filters/static-filter-checker.js:116:14)
      at GraphCompiler.gen_ReadProc (lib/compiler/graph-compiler.js:435:21)
      at GraphCompiler.gen_proc_element (lib/compiler/graph-compiler.js:370:39)
      at GraphCompiler.gen_procs (lib/compiler/graph-compiler.js:123:25)
      at GraphCompiler.gen (lib/compiler/graph-compiler.js:68:22)
      at stages.compile (lib/compiler/index.js:43:25)
      at lib/compiler/index.js:88:20
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)
```

It should be a valid filter.

**Comment by dmajda** [comment] 2016-03-01 15:35
Do you have any use case for the `*` operator in a static filter setting which can’t be fulfilled by a simple field reference?

I removed support for `*` in static filters because it is dynamic in nature and can’t be compiled into native queries in general. The fact that it worked in static filters before in limited form (with an argument resolving to a string in build-time) was a coincidence caused by AST representation of `field` and `*"field"` being the same. This got rectified in #327 with introduction of `Field`.

**Comment by davidvgalbraith** [comment] 2016-03-01 19:51
I do! It's field names with spaces or illegal characters. E.g the Juttle Elastic Adapter has @timestamp for its default timeField which you can't filter on without *"@timestamp".

**Comment by dmajda** [comment] 2016-03-02 15:50
Good point, we have no other way to escape these.

I re-added limited `*"field"` support in #500. The approach differs from yours in that it allows only limited form of `*` syntax (with string literals) and — more importantly — it still produces `Field` nodes, so everything is transparent for the adapters.

**Closed** 2016-03-02 16:15 UTC
Labels: in progress
